# Generated by Django 5.1.7 on 2026-03-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="App",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("tagline", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("science", "Science"),
                            ("weather", "Weather"),
                            ("education", "Education"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("emoji", models.CharField(default="📱", max_length=10)),
                ("app_store_url", models.URLField(blank=True)),
                ("play_store_url", models.URLField(blank=True)),
                ("support_email", models.EmailField(blank=True, max_length=254)),
                (
                    "support_url_notes",
                    models.TextField(
                        blank=True,
                        help_text="Extra info shown on the /support/ page for this app",
                    ),
                ),
                (
                    "privacy_policy",
                    models.TextField(
                        blank=True,
                        help_text="App-specific privacy policy text (Markdown supported)",
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#5dcaa5",
                        help_text="CSS color for this app's accent (hex or var(...))",
                        max_length=20,
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
    ]
